### ISSUE TITLE
GPM Changing to Youtube Music

### ISSUE THREAD

**Issue by CombatMedic02** [regularwave/PlayBack-to-Text#1]
Shot in the dark but I wondered if you were still around/supporting this simple yet super useful program. Google Play Music is finally getting discontinued and it would be great if this program was updated to work with the new Youtube Music player. It looks like a similar player, it would just be awesome to continue being able to use this program for my stream and I'm sure there is still a good number of people out there who still also use it. :)

Thanks in advance,

CombatMedic02

**Comment by regularwave** [comment]
Unfortunately, I no longer use GPMDP and - as far as I can tell - the app iteself is no longer maintained.
